import uinput

KEY_CODES = {
    1: uinput.KEY_1,
    2: uinput.KEY_2,
    3: uinput.KEY_3,
    4: uinput.KEY_4,
    5: uinput.KEY_5,
    6: uinput.KEY_6,
    7: uinput.KEY_7,
    8: uinput.KEY_8,
    9: uinput.KEY_9,
    10: uinput.KEY_0,
    11: uinput.KEY_Q,
    12: uinput.KEY_W,
    13: uinput.KEY_E,
    14: uinput.KEY_R,
    15: uinput.KEY_T,
    16: uinput.KEY_Y,
    17: uinput.KEY_U,
    18: uinput.KEY_I,
    19: uinput.KEY_O,
    20: uinput.KEY_P,
    21: uinput.KEY_A,
    22: uinput.KEY_S,
    23: uinput.KEY_D,
    24: uinput.KEY_F,
    25: uinput.KEY_G,
    26: uinput.KEY_H,
    27: uinput.KEY_J,
    28: uinput.KEY_K,
    29: uinput.KEY_L,
    30: uinput.KEY_SEMICOLON,
    31: uinput.KEY_LEFTSHIFT,
    32: uinput.KEY_Z,
    33: uinput.KEY_X,
    34: uinput.KEY_C,
    35: uinput.KEY_V,
    36: uinput.KEY_B,
    37: uinput.KEY_N,
    38: uinput.KEY_M,
    39: uinput.KEY_COMMA,
    40: uinput.KEY_DOT,
    41: uinput.KEY_LEFTCTRL,
    42: uinput.KEY_LEFTALT,
    43: uinput.KEY_SPACE,
    44: uinput.KEY_SLASH,
    45: uinput.KEY_APOSTROPHE,
    46: uinput.KEY_TAB,
    47: uinput.KEY_KPPLUS,
    48: uinput.KEY_KPMINUS,
    49: uinput.KEY_BACKSPACE,
    50: uinput.KEY_ENTER    
}

MODIFIER_KEYS = [
    uinput.KEY_LEFTSHIFT,
    uinput.KEY_LEFTCTRL,
    uinput.KEY_LEFTALT
]
